name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          jmeter -n -t Login_Demo.jmx -l result.jtl -e -o reports/html

      - name: Debug
        run: |
          find . -type f

      - name: Upload JTL file
        uses: actions/upload-artifact@v4
        with:
          name: result-jtl
          path: result.jtl

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/html
