name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: './Login_Demo.jmx'

      - name: Upload JMeter Results (JTL)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: ./result.jtl
